name: Deepnote Custom Images

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deepnote_images.yml'
      - 'DeepnoteDockerfile'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/deepnote-dicoding-msml

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: test-and-build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          context: git
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          # use already cloned repository
          context: .
          file: ./DeepnoteDockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
