name: Flutter CI/CD

on:
  push:
    branches: [ flutter-restaurant-app ]
  pull_request:
    branches: [ flutter-restaurant-app ]

jobs:
  build:
    name: Analyze, Test, and Build
    runs-on: ubuntu-latest
    environment: test-and-build
    env:
      # already use Android 16.0 ("Baklava") Tag/ABI: google_apis_playstore/x86_64
      emulator-profile: 'pixel'
      avd-cache-key: 'avd-profile-pixel'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # can be use for other purpose like flutter pub get, etc
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_GITHUB_REPO }}

      - name: Checkout Private Repo
        uses: actions/checkout@v6
        with:
          repository: ${{ secrets.GIT_PRIVATE_REPO }}
          ssh-key: ${{ secrets.SSH_PRIVATE_GITHUB_REPO }}
          # specific branch
          ref: ${{ vars.GIT_PRIVATE_REPO_BRANCH }}
          fetch-depth: 2
          # the data will store in folder `private-repo`
          path: private-repo

      - name: Setup Java
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: 'temurin'
          # much smaller, only 141MB
          java-version: '25'
          # see https://github.com/actions/setup-java/raw/refs/heads/main/docs/advanced-usage.md
          java-package: 'jdk'
      - run: java --version          
        
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

        # save gradle cache (library, configuration, etc)
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5

        # save Android Virtual Device
      - name: AVD cache
        uses: actions/cache@v5
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ env.avd-cache-key }}

        # generate AVD snapshots if it was no cache
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: ${{ env.emulator-profile }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          disable-spellchecker: false
          script: echo "Generated AVD snapshot for caching..."

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter doctor -v
          
      - name: Install Dependencies
        run: cd private-repo && flutter pub get
        
      - name: Flutter Analyze
        run: cd private-repo && flutter analyze
        
      - name: Flutter Test
        run: cd private-repo && flutter test

      - name: Run Integration Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: ${{ env.emulator-profile }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disable-spellchecker: true
          script: flutter test integration_test/app_test.dart
        
      - name: Build Release APK
        # targets:
        #   app-armeabi-v7a-release.apk for old gadget
        #   app-arm64-v8a-release.apk for modern gadget
        #   app-x86_64-release.apk  for emulator
        run: cd private-repo && flutter build apk --release --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # only take a path
          path: private-repo/build/app/outputs/flutter-apk/*-release.apk
