name: Build and Push to GHCR

on:
  push:
    branches: [ nodejs-money-tracker-backend ]
    paths:
      - '.github/workflows/github_containers.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/money-tracker-backend

jobs:
  money-tracker-backend:
    runs-on: ubuntu-latest
    environment: test-and-build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v6
        with:
          repository: ${{ secrets.NODEJS_MONEY_TRACKER_REPO }}
          ssh-key: ${{ secrets.SSH_NODEJS_MONEY_TRACKER_REPO }}
          ref: ${{ vars.NODEJS_MONEY_TRACKER_REPO_BRANCH }}
          fetch-depth: 2

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          file: ./Dockerfile.local
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

