name: Cache Preparation

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/prepare-and-cache.yml'
  # Manual action with button in Github UI
  workflow_dispatch:

env:
  # Global configuration for consistency across jobs
  EMULATOR_PROFILE: 'pixel'
  # use Android 16.0 ("Baklava")
  ANDROID_API_LEVEL: ${{ vars.ANDROID_API_LEVEL || '36' }}
  ANDROID_IMAGE: ${{ vars.ANDROID_IMAGE || 'google_apis' }}
  ANDROID_ARCH: ${{ vars.ANDROID_ARCH || 'x86_64' }}
  AVD_NAME: 'test'
  JAVA_VERSION: ${{ vars.JAVA_VERSION || '21' }}
  # much smaller, only 207MB for temurin-jdk-21
  JAVA_DISTRO: ${{ vars.JAVA_DISTRO || 'temurin' }}
  # see https://github.com/actions/setup-java/raw/refs/heads/main/docs/advanced-usage.md
  JAVA_VARIANT: ${{ vars.JAVA_VARIANT || 'jdk' }}
  FLUTTER_CHANNEL: ${{ vars.FLUTTER_CHANNEL || 'stable' }}
  # will be override it with dynamic value
  AVD_CACHE_KEY: ''

jobs:
  build:
    name: Prepare Cache
    runs-on: ubuntu-latest
    environment: test-and-build
    steps:
      - name: Set dynamic env
        run: |
          echo "AVD_CACHE_KEY=avd-${{ env.AVD_NAME }}-${{ env.EMULATOR_PROFILE }}-${{ env.ANDROID_API_LEVEL }}-${{ env.ANDROID_IMAGE }}-${{ env.ANDROID_ARCH }}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          java-package: ${{ env.JAVA_VARIANT }}

        # save gradle cache (library, configuration, etc)
      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

        # save Android Virtual Device
      - name: AVD Cache
        uses: actions/cache@v5
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ env.AVD_CACHE_KEY }}

      - name: Create AVD Snapshot (if no cache)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          profile: ${{ env.EMULATOR_PROFILE }}
          target: ${{ env.ANDROID_IMAGE }}
          arch: ${{ env.ANDROID_ARCH }}
          avd-name: ${{ env.AVD_NAME }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          disable-spellchecker: false
          script: flutter doctor -v && echo "AVD snapshot created and cached."
