name: Check system Specs

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/spec.yml'
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: System Specs
      run: |
        lscpu
        cat /proc/cpuinfo
        echo "Memory:"
        free -h
        echo "Disk Space:"
        df -h /
        vmstat 1 2
