name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/spec.yml'
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: System Specs
      run: |
        cat /proc/cpuinfo | egrep -m 1 "^model name"
        cat /proc/cpuinfo | egrep -m 1 "^cpu MHz"
        cat /proc/cpuinfo | egrep -m 1 "^cpu cores"
        echo "Memory:"
        free -h
        echo "Disk Space:"
        df -h /
